config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books
  resources :likes
  get 'matching', to: 'pages#matching', as: 'matching'
  get 'matchmaking', to: 'pages#matchmaking', as: 'matchmaking'
  resources :matches do
    resources :messages, only: :create
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord
  has_many_attached :photos
  acts_as_taggable_on :tags
  acts_as_taggable_on :genres
  has_many :likes
  belongs_to :user
  GENRES = ['Fantasia', 'Terror', 'Ficção Científica', 'Romance', 'Mistério', 'Aventura', 'Drama', 'Distopia', 'Suspense', 'Biografia']
  enum condition: { novo: 0, usado: 1, danificado: 2, colecionador: 3 }

 validates :title, :author, :publisher, :condition, presence: true
 validates :photos, presence: true
end

app/controllers/books_controller.rb
# class BooksController < ApplicationController
#   before_action :set_book, only: %i[show edit update destroy]
#   def index
#     @books = current_user.books
#     @book = Book.all
#   end
#   def new
#     @book = Book.new
#   end

#   def create
#     @book = Book.new(book_params)
#     if @book.tag_list.empty?
#       render :new, status: :unprocessable_entity
#     else
#       @book.user = current_user
#       @book.tag_list = book_params[:tag_list]
#       if @book.save
#         redirect_to books_path, notice: "Successfully created book"
#       else
#         render :new, status: :unprocessable_entity
#       end
#     end
#   end


#   def show
#     @books = Book.all
#     # Armazena na sessão apenas os livros que não pertencem ao usuário logado
#     if session[:books].nil?
#       session[:books] = Book.where.not(user_id: current_user.id).shuffle.map(&:id)
#     end

#     # Pega o próximo livro do array (se existir)
#     @book_id = session[:books].shift

#     if @book_id
#       @book = Book.find(@book_id)
#     else
#       # Se não houver mais livros, reinicia o array sem os livros do usuário
#       session[:books] = Book.where.not(user_id: current_user.id).shuffle.map(&:id)
#       @book_id = session[:books].shift
#       @book = Book.find(@book_id) if @book_id
#     end
#   end

#   def update
#     if @book.update(book_params)
#       redirect_to book_path(@book), notice: "Livro atualizado com sucesso."
#     else
#       render :edit, status: :unprocessable_entity
#     end
#   end

#   def destroy

#     likes = Like.where(book_id: @book.id)

#     matches = Match.where(first_like_id: likes.pluck(:id)).or(Match.where(second_like_id: likes.pluck(:id)))

#     matches.destroy_all if matches

#     likes.destroy_all if likes

#     @book.destroy

#     redirect_to books_path, notice: "Livro removido com sucesso."
#   end

#   private

#   def accept
#     # Aqui você pode adicionar lógica para registrar que o usuário aceitou o livro
#     redirect_to books_path # Redireciona para o próximo livro
#   end

#   def reject
#     # Aqui você pode adicionar lógica para registrar que o usuário recusou o livro
#     redirect_to books_path # Redireciona para o próximo livro
#   end


#   def set_book
#     @book = Book.find(params[:id])
#     @user = current_user
#   end

#   def book_params
#     params.require(:book).permit(:title, :author, :publisher, :condition, :tag_list, photos: [])
#   end
# end


#---------- Sugestions ----------

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = current_user.books
    @book = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user

    if @book.tag_list.empty?
      flash[:alert] = "O livro precisa ter ao menos uma tag!"
      render :new, status: :unprocessable_entity
    elsif @book.save
      redirect_to books_path, notice: "Livro criado com sucesso!"
    else
      flash[:alert] = "Erro ao salvar o livro."
      render :new, status: :unprocessable_entity
    end
  end

  def show
    if session[:books].nil? || session[:books].empty?
      session[:books] = Book.where.not(user_id: current_user.id).shuffle.map(&:id)
    end

    @book_id = session[:books].shift
    @book = Book.find_by(id: @book_id)

    unless @book
      session[:books] = Book.where.not(user_id: current_user.id).shuffle.map(&:id)
      @book = Book.find_by(id: session[:books].shift)
    end
  end

  def update
    if @book.update(book_params)
      redirect_to books_path, notice: "Livro atualizado com sucesso."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    likes = Like.where(book_id: @book.id)
    matches = Match.where(first_like_id: likes.pluck(:id)).or(Match.where(second_like_id: likes.pluck(:id)))

    matches.destroy_all if matches.any?
    likes.destroy_all if likes.any?

    @book.destroy
    redirect_to books_path, notice: "Livro removido com sucesso."
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :condition, :tag_list, photos: [])
  end
end

app/views/books/edit.html.erb
<div class="white-container index-books-menu">
  <div class="icon-right">
    <%= link_to books_path, method: :delete do %>
      <%= image_tag "arrow-left.png", alt: "Voltar" %>
    <% end %>
  </div>

  <div class="logo-black index-books-logo" id="index-books-logo">
    <%= image_tag "logo-black.png", alt: "Logo BookMatch" %>
  </div>

  <div class="icon-left"></div>

  <%= link_to edit_user_registration_path do %>
    <div class="icon-left" id="index-books-settings">
      <%= image_tag "settings.png", alt: "Configurações" %>
    </div>
  <% end %>

  <div class="main-image-avatar">
    <% if current_user.photo.attached? %>
      <%= image_tag current_user.photo, width: 100, height: 100 %>
    <% else %>
      <%= image_tag "no-image.jpg", width: 100, height: 100 %>
    <% end %>
  </div>
</div>

<div class="master-container" id="index-books-container">
  <div class="top-container container-image">
    <p class="top"><%= current_user.full_name.split.map(&:capitalize).join(' ') %></p>
  </div>


    <div class="top-white-container index-books-buttons">
      <div class="profile-button">
        <%= link_to books_path, class: "profile-button-my-books-link" do %>
          <button id="profile-button-my-books" class="profile-button-my-books">
            <%= image_tag "my-books.png", alt: "Meus Livros", class: "icon-above" %>
            Meus Livros
          </button>
        <% end %>



        <%= link_to matchmaking_path, class: "profile-button-matches-link" do %>
          <button id="profile-button-matches" class="profile-button-my-books">
            <%= image_tag "matches.png", alt: "Matches", class: "icon-above" %>
            Match
          </button>
        <% end %>

          <%= link_to matches_path, class: "profile-button-my-books-link" do %>
          <button id="profile-button-my-books" class="profile-button-my-books">
            <%= image_tag "chat.png", alt: "Cadastrar Livro", class: "icon-above" %>
            Chat
          </button>
        <% end %>
      </div>
    </div>


    <div class="form">
      <%= simple_form_for @book do |f| %>
        <%= f.input :title,
          required: true,
          label: false,
          input_html: { placeholder: "Título do livro", class: "center-placeholder", style: "background-color: white;" } %>

        <%= f.input :author,
          required: true,
          label: false,
          input_html: { placeholder: "Autor", class: "center-placeholder", style: "background-color: white;" } %>

        <%= f.input :publisher,
          required: true,
          label: false,
          input_html: { placeholder: "Editora", class: "center-placeholder", style: "background-color: white;" } %>

        <%= f.input :condition,
          required: true,
          label: false,
          collection: Book.conditions.keys.map { |key| [key.humanize, key] },
          include_blank: "Estado do livro",
          input_html: { class: "form-select center-placeholder", style: "background-color: white;" } %>

        <div class="form-inputs">
          <%= f.input :tag_list,
            required: true,
            label: false,
            collection: Book::GENRES,
            include_blank: "Gênero",
            input_html: { class: "form-select center-placeholder", style: "background-color: white;" } %>
        </div>

        <div class="form-inputs">
          <%= f.input :photos, label: false, as: :file, input_html: { multiple: true, style: "background-color: white;" } %>
        </div>

        <div class="edit-book-button">
          <%= f.submit "Editar livro", class: "edit-book-button" %>
        </div>
      <% end %>

      <%= button_to "Deletar livro", book_path(@book),
         data: { turbo: false },
         method: :delete,
         class: "cancel-button-link" %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="white-container index-books-menu">
  <div class="icon-right">
    <%= link_to books_path, method: :delete do %>
      <%= image_tag "arrow-left.png", alt: "Voltar" %>
    <% end %>
  </div>

  <div class="logo-black index-books-logo" id="index-books-logo">
    <%= image_tag "logo-black.png", alt: "Logo BookMatch" %>
  </div>

  <div class="icon-left"></div>

  <%= link_to edit_user_registration_path do %>
    <div class="icon-left" id="index-books-settings">
      <%= image_tag "settings.png", alt: "Configurações" %>
    </div>
  <% end %>

  <div class="main-image-avatar">
    <% if current_user.photo.attached? %>
      <%= image_tag current_user.photo, width: 100, height: 100 %>
    <% else %>
      <%= image_tag "no-image.jpg", width: 100, height: 100 %>
    <% end %>
  </div>
</div>

<div class="master-container" id="index-books-container">
  <div class="top-container container-image">
    <p class="top"><%= current_user.full_name.split.map(&:capitalize).join(' ') %></p>
  </div>

  <div class="top-general-container">
    <div class="top-white-container index-books-buttons">
      <div class="profile-button">
        <%= link_to books_path, class: "profile-button-my-books-link" do %>
          <button id="profile-button-my-books" class="profile-button-my-books">
            <%= image_tag "my-books.png", alt: "Meus Livros", class: "icon-above" %>
            Meus Livros
          </button>
        <% end %>



        <%= link_to matchmaking_path, class: "profile-button-matches-link" do %>
          <button id="profile-button-matches" class="profile-button-my-books">
            <%= image_tag "matches.png", alt: "Matches", class: "icon-above" %>
            Match
          </button>
        <% end %>

          <%= link_to matches_path, class: "profile-button-my-books-link" do %>
          <button id="profile-button-my-books" class="profile-button-my-books">
            <%= image_tag "chat.png", alt: "Cadastrar Livro", class: "icon-above" %>
            Chat
          </button>
        <% end %>
      </div>
    </div>

    <div class="book-container-general">
      <% @books.each do |book| %>
        <%= link_to edit_book_path(book), class: "book-container" do %>
          <div class="book-button-photo">
            <% if book.photos.attached? %>
              <li>
                <%= image_tag(book.photos.first, crop: :fill, alt: "#{book.title} photo") %>
              </li>
            <% end %>
          </div>
          <div class="book-button-info">
            <ul>
              <li><%= book.title %></li>
              <li><%= book.author %></li>
              <li><%= book.condition.capitalize %></li>
            </ul>
          </div>
        <% end %>

      <% end %>

      <%= link_to new_book_path(:user), class: "add-book-button" do %>
        <span>Adicionar livro</span>
      <% end %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="white-container index-books-menu">
  <div class="icon-right">
    <%= link_to books_path, method: :delete do %>
      <%= image_tag "arrow-left.png", alt: "Voltar" %>
    <% end %>
  </div>

  <div class="logo-black index-books-logo" id="index-books-logo">
    <%= image_tag "logo-black.png", alt: "Logo BookMatch" %>
  </div>

  <div class="icon-left"></div>

  <%= link_to edit_user_registration_path do %>
    <div class="icon-left" id="index-books-settings">
      <%= image_tag "settings.png", alt: "Configurações" %>
    </div>
  <% end %>

  <div class="main-image-avatar">
    <% if current_user.photo.attached? %>
      <%= image_tag current_user.photo, width: 100, height: 100 %>
    <% else %>
      <%= image_tag "no-image.jpg", width: 100, height: 100 %>
    <% end %>
  </div>
</div>

<div class="master-container" id="index-books-container">
  <div class="top-container container-image">
    <p class="top"><%= current_user.full_name.split.map(&:capitalize).join(' ') %></p>
  </div>

    <div class="top-white-container index-books-buttons">
      <div class="profile-button">
        <%= link_to books_path, class: "profile-button-my-books-link" do %>
          <button id="profile-button-my-books" class="profile-button-my-books">
            <%= image_tag "my-books.png", alt: "Meus Livros", class: "icon-above" %>
            Meus Livros
          </button>
        <% end %>



        <%= link_to matchmaking_path, class: "profile-button-matches-link" do %>
          <button id="profile-button-matches" class="profile-button-my-books">
            <%= image_tag "matches.png", alt: "Matches", class: "icon-above" %>
            Match
          </button>
        <% end %>

          <%= link_to matches_path, class: "profile-button-my-books-link" do %>
          <button id="profile-button-my-books" class="profile-button-my-books">
            <%= image_tag "chat.png", alt: "Cadastrar Livro", class: "icon-above" %>
            Chat
          </button>
        <% end %>
      </div>
    </div>


    <div class="form">
      <%= simple_form_for @book do |f| %>
        <%= f.input :title,
          required: true,
          label: false,
          input_html: { placeholder: "Título do livro", class: "center-placeholder", style: "background-color: white;" } %>

        <%= f.input :author,
          required: true,
          label: false,
          input_html: { placeholder: "Autor", class: "center-placeholder", style: "background-color: white;" } %>

        <%= f.input :publisher,
          required: true,
          label: false,
          input_html: { placeholder: "Editora", class: "center-placeholder", style: "background-color: white;" } %>

        <%= f.input :condition,
          required: true,
          label: false,
          collection: Book.conditions.keys.map { |key| [key.humanize, key] },
          include_blank: "Estado do livro",
          input_html: { class: "form-select center-placeholder", style: "background-color: white;" } %>

        <div class="form-inputs">
          <%= f.input :tag_list,
            required: true,
            label: false,
            collection: Book::GENRES,
            include_blank: "Gênero",
            input_html: { class: "form-select center-placeholder", style: "background-color: white;" } %>
        </div>

        <div class="form-inputs">
          <%= f.input :photos, label: false, as: :file, input_html: { multiple: true, style: "background-color: white;" } %>
        </div>

        <div class="add-book-button-form">
          <%= f.submit "Adicionar livro", class: "add-book-button-form" %>
        </div>
      <% end %>
    </div>
  </div>
</div>