config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books
  resources :likes
  get 'matching', to: 'pages#matching', as: 'matching'
  get 'matchmaking', to: 'pages#matchmaking', as: 'matchmaking'
  resources :matches do
    resources :messages, only: :create
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :first_like, class_name: "Like", foreign_key: "first_like_id"
  belongs_to :second_like, class_name: "Like", foreign_key: "second_like_id"

  has_many :messages, dependent: :destroy
end

app/controllers/matches_controller.rb
# class MatchesController < ApplicationController
#   before_action :match_params, only: [:create]

#   def index
#     @matches = Match.includes(:first_like, :second_like)
#     .where(first_like: { user_id: current_user.id })
#     .or(Match.where(second_like: { user_id: current_user.id }))

#   end


#   def new
#     @match = Match.new
#   end


#   def show
#     @match = Match.find(params[:id])
#     @message = Message.new
#     @user = current_user
#     @match.messages.unread_by(current_user).update_all(read: true)
#   end


#   def create
#     @match = Match.new(match_params)
#     if @match.save
#       flash[:notice] = "Match registrado com sucesso!"
#       redirect_to matching_path
#     else
#       render :new
#     end
#   end

#   def destroy
#     @match = Match.find(params[:id])
#     @match.destroy
#     redirect_to matches_path
#   end


#   private
#   def match_params
#     params.require(:match).permit(:first_like_id, :second_like_id)
#   end

# end


#-------Sugestions-------
class MatchesController < ApplicationController
  def index
    @matches = Match.joins(:first_like, :second_like)
                    .where("likes.user_id = ? OR second_likes_matches.user_id = ?", current_user.id, current_user.id)
                    .includes(:first_like, :second_like)
  end

  def show
    @match = Match.find(params[:id])
    @message = Message.new
    @user = current_user
    @match.messages.unread_by(current_user).update_all(read: true)
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to matches_path, notice: "Match removido com sucesso."
  end
end

app/views/matches/index.html.erb
<div class="white-container">
  <div class="icon-right">
    <%= link_to books_path do %>
      <%= image_tag "arrow-left-black.png", alt: "Voltar" %>
    <% end %>
  </div>

  <div class="logo-black">
    <%= image_tag "logo-black.png", alt: "Logo BookMatch" %>
  </div>

  <div class="icon-left">
    <%= image_tag "settings.png", alt: "Configurações" %>
  </div>
</div>

<div class="matches-index-chat">
  <% if @matches.any? %>
    <div id="index-avatar-container">
      <% shown_users = Set.new %>
      <% @matches.each do |match| %>
        <% if match.first_like.user.id == current_user.id %>
          <% second_user = match.second_like.user %>
        <% else %>
          <% second_user = match.first_like.user %>
        <% end %>

        <% unless shown_users.include?(second_user.id) %>
          <% shown_users.add(second_user.id) %>
          <div class="index-avatar-profile">
            <% if second_user.present? && second_user.photo.present? %>
              <%= image_tag second_user.photo, width: 150, height: 150,
                alt: "#{second_user.email} photo", class: "avatar-index-photo" %>
            <% else %>
              <%= image_tag "no-image.jpg", width: 150, height: 150,
                alt: "Sem foto disponível", class: "avatar-index-photo" %>
            <% end %>
            <p><%= second_user.full_name.split.first %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="master-container">
    <div class="white-container-match">
      <div class="top-match">
        <p>Mensagens</p>
      </div>

      <div id="index-message-container">
        <ul>
          <% @matches.each do |match| %>
            <% if match.first_like.user.id == current_user.id %>
              <% second_user = match.second_like.user %>
            <% else %>
              <% second_user = match.first_like.user %>
            <% end %>

            <% unread_messages_count = match.messages.unread_by(current_user).count %>

            <%= link_to match_path(match), class: "chat-link" do %>
              <div class="chat-container">
                <div class="avatar-message-container">
                  <% if second_user.present? && second_user.photo.present? %>
                    <%= image_tag second_user.photo, width: 150, height: 150,
                      gravity: :center, crop: :fill,
                      alt: "#{second_user.email} photo", class: "avatar-index-photo" %>
                  <% else %>
                    <%= image_tag "no-image.jpg", width: 150, height: 150,
                      alt: "Sem foto disponível", class: "avatar-index-photo" %>
                  <% end %>
                </div>

                <div class="relative-positioning">
                  <div class="index-info-message">
                    <h3><%= second_user.full_name.split.first %></h3>
                    <% last_message = match.messages.order(created_at: :desc).limit(1).take %>
                    <% if last_message.present? %>
                      <p class="message-content-index">
                        <i class="fa-solid <%= last_message.user == current_user ? 'fa-share' : 'fa-reply' %>"></i>

                        <%= last_message.content.length > 17 ? last_message.content[0, 17] + "..." : last_message.content[0, 20] %>

                      </p>
                    <% else %>
                      <p>
                        <%= match.first_like.user == current_user ? match.second_like.book.title : match.first_like.book.title %>
                      </p>
                    <% end %>
                  </div>
                </div>

                <div id="index-message-alert-time">
                  <%= match.created_at.strftime("%H:%M") %>
                  <% if unread_messages_count.positive? %>
                    <span class="unread-badge"><%= unread_messages_count %></span>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <% else %>
    <p class="matching-no-matches">Você ainda não tem matches.<br>😞</p>
  <% end %>
</div>

app/views/matches/show.html.erb
<div class="white-container">
  <div class="icon-right">
    <%= link_to books_path do %>
      <%= image_tag "arrow-left-black.png", alt: "Voltar" %>
    <% end %>
  </div>

  <div class="logo-black">
    <%= image_tag "logo-black.png", alt: "Logo BookMatch" %>
  </div>

  <div class="icon-left">
    <%= image_tag "settings.png", alt: "Procurar" %>
  </div>
</div>

<!-- Turbo Streams para atualização do chat -->
<%= turbo_stream_from "match_#{@match.id}_messages" %>

<div class="chat">
  <div class="chat-message-container">
    <div id="messages" class="messages">
      <% @match.messages.each do |message| %>
        <%= render partial: "messages/message",  locals: { message: message, user: current_user } %>
      <% end %>
    </div>
  </div>
</div>

<div class="chat">
  <% other_user = (current_user.id == Like.find(@match.first_like_id).user_id) ?
      Like.find(@match.second_like_id).user :
      Like.find(@match.first_like_id).user %>
</div>

<div class="form-centralizer">
<!-- Formulário para envio de mensagens -->
  <%= simple_form_for [@match, @message], html: {
    class: "d-flex",
    data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset", target: "reset-form.form" }
  } do |f| %>

    <div class="send">
      <div class="chat-input-container justify-content-center">
        <%= f.input :content,
          label: false,
          placeholder: "Escreva aqui sua mensagem...",
          style: "background-color: #FFFCFC; color: #222222;",
          class: "message-input" %>
        <%= f.submit "Enviar", class: "send-button" %>
      </div>
    </div>
  <% end %>
</div>